### ISSUE TITLE
perguntas gerais e específicas

### ISSUE THREAD

**Issue by ghost** [Na18k/Conversor-de-Letras#1]
Olá a todos.

Se possível e caso tenha tempo gostaria de saber algumas coisas.
1. qual é a licença desse projeto, por exemplo, é MIT, Apache, GPL? (quero ver se a licença do projeto é compatível com a licença do projeto que estou desenvolvendo que nesse caso é MIT). 
2. posso utilizar esse projeto para um projeto equivalente ao qual estou desenvolvendo?

*Aguardo se possível uma breve resposta*

**Comment by kainandev** [comment]
Olá, adorei sei interessante pelo meu projeto, agradeço o reconhecimento.

 Referente ao projeto a licença é MIT, mais as fontes usadas podem ter direitos autorais atribuidos a elas, peço que tome cuidado com esse quisito.

 Sim pode utilizar meu projeto.
 Só peço apenas que a LNK (Letras e números de Kainan) sejam prestadas os créditos,  já que são de minha autoria de criação própria e possuo um carinho por ela, e não gostaria que fossem desconhecido seu criador; elas não entram na Licensa MIT, mais permito a utilização dessa cifra/idioma para uso sem fins lucrativos, e creditadas.

**Comment by ghost** [comment]
Oi Na18k, obrigado pelo feedback.

**Comment by kainandev** [comment]
De nada :)

Adorei seu projeto, vá em frente pois, esse é um projeto incrível. 🙂
